language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-opsgenie.gemspec
- gem install sensu-plugins-opsgenie-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: K0vq7Ahny7bZIz1LnilosmNgHG/L4Nv6QuPaxo++/lQ7dWT9puRDLFw/pQI7+Xgb+LBLWFW2ye33q01qd1Cke8nuMKQduxnGeBzzH6fHJiXDcz5uEoKB2a8qdkwHHP3y9fisGaZgyhxlmui3fny3C0JjFizs9oNNYIt3MZcETTk=
  gem: sensu-plugins-opsgenie
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-opsgenie
